### ISSUE TITLE
Having an option to not to build for mobile architectures

### ISSUE THREAD

**Issue by zhihaoy** [ginkgo-project/CudaArchitectureSelector#2]
We don't want to build for 6.2; it would be nice if there is a way to filter out Tegra, Jetson, DRIVE support.

**Comment by tcojean** [comment]
Sorry for the long time to answer this issue, I completely missed this. Most likely this is not an issue anymore.
If it still is, I think it should be enough to simply add `UNSUPPORTED "62"` to the function calls. For completeness, I don't think we should remove 62 out of CAS altogether.

For these reasons, I'll be closing this for now.
